dist: trusty # use Travis Trusty env (http://docs.travis-ci.com/user/ci-environment/)
sudo: required
language: php
php:
  - '7.0'

addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

before_install:
# Remove xdebug to speed up composer
  - phpenv config-rm xdebug.ini
# Get auth keys: http://devdocs.magento.com/guides/v2.0/install-gde/prereq/connect-auth.html
  - composer config -g http-basic.repo.magento.com $M2_KEY_PUB $M2_KEY_PRIV
# Copy Travis CI configuration from template and deploy Magento 2 application
  - pwd # control current path ('LOCAL_ROOT' in templates.json)
  - cp deploy_cfg.sh.travis deploy_cfg.sh # create configuration for Travis from template
  - sh deploy.sh

script:
  - php ./work/vendor/bin/phpunit -c work/vendor/flancer32/sample_mage2_module/test/unit/phpunit.dist.xml
  - php ./work/vendor/bin/phpunit -c work/vendor/flancer32/sample_mage2_module/test/functional/phpunit.dist.xml
#  - php ./work/vendor/bin/phpunit - ./work/dev/tests/unit/phpunit.xml.dist # run Magento 2 unit tests

notifications:
  email:
    recipients:
      - flancer64@gmail.com
    on_success: change # [always|never|change], default: change
    on_failure: change # [always|never|change], default: change